/**
 * Emits SQL that imports the five advisories published by the previous GNA-115
 * site as published GCVE records, so the registry endpoints keep serving them.
 *
 * Data snapshot: scripts/legacy-dump.json, originally served by
 * https://32b0a928.cve-disclosure-site.pages.dev/api/gcve/dump
 */
import { formatGcveId, formatSubmissionReference } from "../src/shared/gcve-id";
import { buildGcveRecord } from "../src/shared/record-builder";
import dump from "./legacy-dump.json";

const GCVE_YEAR = 2026;
const REFERENCE_YEAR = 2018;
const PUBLISHED_AT = "2026-09-16T00:00:00.000Z";

type LegacyEntry = {
  cveId: string;
  title: string;
  severity: string;
  cvssScore: string;
  vulnerabilityType: string;
  datePublished: string;
  affectedSoftware: string;
  affectedVersions: string;
  description: string;
  technicalDetails: string;
  poc: string;
  credits: string;
  references: string;
  id: string;
};

const entries: LegacyEntry[] = dump.vulnerabilities;

const sqlText = (value: string | null) => (value === null ? "NULL" : `'${value.replace(/'/g, "''")}'`);
const sqlNumber = (value: number | null) => (value === null ? "NULL" : String(value));

/** vendor is the first token of the legacy affectedSoftware field. */
const splitSoftware = (affectedSoftware: string) => {
  const [vendor, ...rest] = affectedSoftware.trim().split(/\s+/);
  return {
    vendor: vendor ?? affectedSoftware.trim(),
    product: rest.length > 0 ? rest.join(" ") : affectedSoftware.trim(),
  };
};

const lines: string[] = ["-- Generated by scripts/seed-legacy.ts"];

entries.forEach((entry, index) => {
  const sequence = index + 1;
  const gcveId = formatGcveId(GCVE_YEAR, sequence);
  const reference = formatSubmissionReference(REFERENCE_YEAR, sequence);
  const { vendor, product } = splitSoftware(entry.affectedSoftware);
  const references = entry.references
    .split("\n")
    .map((url) => url.trim())
    .filter(Boolean);
  const cvssScore = entry.cvssScore.trim() === "" ? null : Number(entry.cvssScore);
  const cweIds = entry.technicalDetails.includes("CWE-862") ? "CWE-862" : null;

  const record = buildGcveRecord(
    {
      title: entry.title,
      vulnerabilityType: entry.vulnerabilityType,
      vendor,
      product,
      affectedVersions: entry.affectedVersions.trim(),
      cveId: entry.cveId,
      cweIds,
      cvssScore,
      cvssVector: null,
      description: entry.description,
      technicalDetails: entry.technicalDetails,
      poc: entry.poc,
      references,
      reporterName: entry.credits,
      datePublic: entry.datePublished,
    },
    gcveId,
    PUBLISHED_AT,
  );

  lines.push(
    `INSERT OR IGNORE INTO submissions (id, reference, reference_year, reference_seq, status, title, ` +
      `vulnerability_type, vendor, product, affected_versions, cve_id, cwe_ids, severity, cvss_score, ` +
      `cvss_vector, description, technical_details, poc, references_json, reporter_name, reporter_email, ` +
      `reporter_org, reporter_note, ip_hash, created_at, updated_at) VALUES (` +
      [
        sqlText(`seed-${entry.cveId}`),
        sqlText(reference),
        String(REFERENCE_YEAR),
        String(sequence),
        sqlText("published"),
        sqlText(entry.title),
        sqlText(entry.vulnerabilityType),
        sqlText(vendor),
        sqlText(product),
        sqlText(entry.affectedVersions.trim()),
        sqlText(entry.cveId),
        sqlText(cweIds),
        sqlText(entry.severity.trim().toLowerCase()),
        sqlNumber(cvssScore),
        "NULL",
        sqlText(entry.description),
        sqlText(entry.technicalDetails),
        sqlText(entry.poc),
        sqlText(JSON.stringify(references)),
        sqlText(entry.credits),
        "NULL",
        "NULL",
        "NULL",
        "NULL",
        sqlText(PUBLISHED_AT),
        sqlText(PUBLISHED_AT),
      ].join(", ") +
      ");",
  );

  lines.push(
    `INSERT OR IGNORE INTO gcves (id, year, seq, submission_id, cve_ref, record_json, published_at, updated_at) VALUES (` +
      [
        sqlText(gcveId),
        String(GCVE_YEAR),
        String(sequence),
        sqlText(`seed-${entry.cveId}`),
        sqlText(entry.cveId),
        sqlText(JSON.stringify(record)),
        sqlText(PUBLISHED_AT),
        sqlText(PUBLISHED_AT),
      ].join(", ") +
      ");",
  );
});

console.log(lines.join("\n"));
